apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "frontend-service"
        dapr.io/app-port: "5003"
        dapr.io/config: "tracing"
    spec:
      containers:
        - name: frontend-container
          image: "localhost/frontend-service:local"
          ports:
            - containerPort: 5003

